var ccb_resources = [
    {type:'ccbi', src:"MainScene.ccbi"},
    {type:'image', src:"thebg.png"},
    {type:'ccbi', src:"playerframe.ccbi"},
    {type:'image', src:"allchars.png"},
    {type:'ccbi', src:"cardFrame.ccbi"},
    {type:'image', src:"ccbResources/ccbParticleFire.png"},
    {type:'image', src:"clickme.png"},
    {type:'plist', src:"allui.plist"},
    {type:'image', src:"allui.png"},
    {type:'plist', src:"allchars.plist"},
    {type:'image', src:"ccbResources/ccbParticleStars.png"},
    {type:'image', src:"numbg.png"},
    {type:'ccbi', src:"monFrame.ccbi"},
    {type:'ccbi', src:"GameScene.ccbi"},
    {type:'image', src:"clickme-down.png"},
    {type:'image', src:"ccbResources/ccbParticleSmoke.png"},
    {type:'image', src:"ccbResources/ccbParticleSnow.png"},
];
